# 玩家加入传送的组
player-join: 'example'
# 玩家掉入虚空传送的组
fall-to-void: 'example'

spawns:
  example:
    # 多个位置
    locations:
    # world,x,y,z,yaw,pitch
    # x,y,z,yaw,pitch
    # world,x,y,z
    # x,y,z
    # any_world 代表所有世界
    - 'any_world,0.5,64.0,0.5,0.0,0.0'
    - 'any_world,0.5,64.0,0.5,180.0,0.0'

    # 节点 locations 的行数, 或 random 来实现随机选取
    # 该节点可不填写
    # 默认为 random
    selection: 'random'